### ISSUE TITLE
Use pydantic's BaseSettings for configuration instead of startlette's config

### ISSUE THREAD

**Issue by robhobbes** [nsidnev/fastapi-realworld-example-app#124]
FastAPI recommends using BaseSettings for confiugration. It would be nice for this example to follow that recommendation. See https://fastapi.tiangolo.com/advanced/settings/

**Comment by nsidnev** [comment]
@robhobbes hi, sorry for long delay, I was busy.

I've used such configuration style in some of my projects and it's real convenient. Unfortunately, I don't have time to write this, but I'm ready to review PRs if someone wants to create them.

This project may be used as an example: https://github.com/mirumon/mirumon-backend
