### ISSUE TITLE
500 error getting articles 

### ISSUE THREAD

**Issue by RubenPozoMolina** [nsidnev/fastapi-realworld-example-app#129]
Testing with zap-api-scan.py I have discovered various 500 status codes in the API. For example:
`curl -X GET "http://localhost:8000/api/articles?tag=%00&author=author&favorited=favorited&limit=20&offset=0" -H  "accept: application/json"`
The complete report look like this:

# ZAP Scanning Report

Generated on Thu, 25 Feb 2021 15:54:01

## Summary of Alerts

| Risk Level | Number of Alerts |
| --- | --- |
| High | 0 |
| Medium | 0 |
| Low | 3 |
| Informational | 1 |

## Alerts

| Name | Risk Level | Number of Instances |
| --- | --- | --- | 
| A Server Error response code was returned by the server | Low | 3 | 
| Unexpected Content-Type was returned | Low | 3 | 
| X-Content-Type-Options Header Missing | Low | 3 | 
| A Client Error response code was returned by the server | Informational | 435 | 

#### Description
<p>A response code of 500 was returned by the server.</p><p>This may indicate that the application is failing to handle unexpected input correctly.</p><p>Raised by the 'Alert on HTTP Response Code Error' script</p>
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=author&favorited=%00&limit=20&offset=0](http://localhost:8000/api/articles?tag=tag&author=author&favorited=%00&limit=20&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 500`
  
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=%00&favorited=favorited&limit=20&offset=0](http://localhost:8000/api/articles?tag=tag&author=%00&favorited=favorited&limit=20&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 500`
  
  
  
  
* URL: [http://localhost:8000/api/articles?tag=%00&author=author&favorited=favorited&limit=20&offset=0](http://localhost:8000/api/articles?tag=%00&author=author&favorited=favorited&limit=20&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 500`
  
  
  
  
Instances: 3
  
### Solution
<p></p>
  
### Reference
* 

  
#### Description
<p>A Content-Type of text/plain was returned by the server.</p><p>This is not one of the types expected to be returned by an API.</p><p>Raised by the 'Alert on Unexpected Content Types' script</p>
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=author&favorited=%00&limit=20&offset=0](http://localhost:8000/api/articles?tag=tag&author=author&favorited=%00&limit=20&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `text/plain`
  
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=%00&favorited=favorited&limit=20&offset=0](http://localhost:8000/api/articles?tag=tag&author=%00&favorited=favorited&limit=20&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `text/plain`
  
  
  
  
* URL: [http://localhost:8000/api/articles?tag=%00&author=author&favorited=favorited&limit=20&offset=0](http://localhost:8000/api/articles?tag=%00&author=author&favorited=favorited&limit=20&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `text/plain`
  
  
  
  
Instances: 3
  
### Solution
<p></p>
  
### Reference
* 

  
#### Description
<p>The Anti-MIME-Sniffing header X-Content-Type-Options was not set to 'nosniff'. This allows older versions of Internet Explorer and Chrome to perform MIME-sniffing on the response body, potentially causing the response body to be interpreted and displayed as a content type other than the declared content type. Current (early 2014) and legacy versions of Firefox will use the declared content type (if one is set), rather than performing MIME-sniffing.</p>
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=0](http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=0)
  
  
  * Method: `GET`
  
  
  * Parameter: `X-Content-Type-Options`
  
  
  
  
* URL: [http://localhost:8000/api/tags](http://localhost:8000/api/tags)
  
  
  * Method: `GET`
  
  
  * Parameter: `X-Content-Type-Options`
  
  
  
  
* URL: [http://localhost:8000/openapi.json](http://localhost:8000/openapi.json)
  
  
  * Method: `GET`
  
  
  * Parameter: `X-Content-Type-Options`
  
  
  
  
Instances: 3
  
### Solution
<p>Ensure that the application/web server sets the Content-Type header appropriately, and that it sets the X-Content-Type-Options header to 'nosniff' for all web pages.</p><p>If possible, ensure that the end user uses a standards-compliant and modern web browser that does not perform MIME-sniffing at all, or that can be directed by the web application/web server to not perform MIME-sniffing.</p>
  
### Other information
<p>This issue still applies to error type pages (401, 403, 500, etc.) as those pages are often still affected by injection issues, in which case there is still concern for browsers sniffing pages away from their actual content type.</p><p>At "High" threshold this scan rule will not alert on client or server error responses.</p>
  
### Reference
* http://msdn.microsoft.com/en-us/library/ie/gg622941%28v=vs.85%29.aspx
* https://owasp.org/www-community/Security_Headers

  
#### Description
<p>A response code of 404 was returned by the server.</p><p>This may indicate that the application is failing to handle unexpected input correctly.</p><p>Raised by the 'Alert on HTTP Response Code Error' script</p>
  
  
  
* URL: [http://localhost:8000/api/articles/658428727677602872](http://localhost:8000/api/articles/658428727677602872)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 404`
  
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=0%26sleep+15%26](http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=0%26sleep+15%26)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 422`
  
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=0%22%3Bcat+%2Fetc%2Fpasswd%3B%22](http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=0%22%3Bcat+%2Fetc%2Fpasswd%3B%22)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 422`
  
  
  
  
* URL: [http://localhost:8000/api/articles/feed?limit=20&offset=0%27%29+UNION+ALL+select+NULL+--+](http://localhost:8000/api/articles/feed?limit=20&offset=0%27%29+UNION+ALL+select+NULL+--+)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 403`
  
  
  
  
* URL: [http://localhost:8000/api/articles/feed?limit=%22%2Bresponse.write%28%5B100%2C000*100%2C000%29%2B%22&offset=0](http://localhost:8000/api/articles/feed?limit=%22%2Bresponse.write%28%5B100%2C000*100%2C000%29%2B%22&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 403`
  
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=776609502133833358.owasp.org&offset=0](http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=776609502133833358.owasp.org&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 422`
  
  
  
  
* URL: [http://localhost:8000/api/articles/feed?limit=www.google.com%3A80%2F&offset=0](http://localhost:8000/api/articles/feed?limit=www.google.com%3A80%2F&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 403`
  
  
  
  
* URL: [http://localhost:8000/api/articles/feed?limit=20&offset=0%3B](http://localhost:8000/api/articles/feed?limit=20&offset=0%3B)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 403`
  
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=%3Bprint%28chr%28122%29.chr%2897%29.chr%28112%29.chr%2895%29.chr%28116%29.chr%28111%29.chr%28107%29.chr%28101%29.chr%28110%29%29%3B](http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=%3Bprint%28chr%28122%29.chr%2897%29.chr%28112%29.chr%2895%29.chr%28116%29.chr%28111%29.chr%28107%29.chr%28101%29.chr%28110%29%29%3B)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 422`
  
  
  
  
* URL: [http://localhost:8000/api/articles/feed?limit=%27&offset=0](http://localhost:8000/api/articles/feed?limit=%27&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 403`
  
  
  
  
* URL: [http://localhost:8000/api/articles/feed?limit=%3Bprint%28chr%28122%29.chr%2897%29.chr%28112%29.chr%2895%29.chr%28116%29.chr%28111%29.chr%28107%29.chr%28101%29.chr%28110%29%29%3B&offset=0](http://localhost:8000/api/articles/feed?limit=%3Bprint%28chr%28122%29.chr%2897%29.chr%28112%29.chr%2895%29.chr%28116%29.chr%28111%29.chr%28107%29.chr%28101%29.chr%28110%29%29%3B&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 403`
  
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=%3Bprint%28chr%28122%29.chr%2897%29.chr%28112%29.chr%2895%29.chr%28116%29.chr%28111%29.chr%28107%29.chr%28101%29.chr%28110%29%29%3B&offset=0](http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=%3Bprint%28chr%28122%29.chr%2897%29.chr%28112%29.chr%2895%29.chr%28116%29.chr%28111%29.chr%28107%29.chr%28101%29.chr%28110%29%29%3B&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 422`
  
  
  
  
* URL: [http://localhost:8000/api/articles/feed?limit=HtTp%3A%2F%2F776609502133833358.owasp.org&offset=0](http://localhost:8000/api/articles/feed?limit=HtTp%3A%2F%2F776609502133833358.owasp.org&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 403`
  
  
  
  
* URL: [http://localhost:8000/api/articles/feed?limit=20%27%7Ctype+%25SYSTEMROOT%25%5Cwin.ini&offset=0](http://localhost:8000/api/articles/feed?limit=20%27%7Ctype+%25SYSTEMROOT%25%5Cwin.ini&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 403`
  
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=any%0D%0ASet-cookie%3A+Tamper%3Dc6833fcd-b6c8-4908-8888-eccc164a99ae%0D%0A](http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=any%0D%0ASet-cookie%3A+Tamper%3Dc6833fcd-b6c8-4908-8888-eccc164a99ae%0D%0A)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 422`
  
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=0%22%26cat+%2Fetc%2Fpasswd%26%22](http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=0%22%26cat+%2Fetc%2Fpasswd%26%22)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 422`
  
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20%22+AND+%221%22%3D%221&offset=0](http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20%22+AND+%221%22%3D%221&offset=0)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 422`
  
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=0%26timeout+%2FT+15](http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=0%26timeout+%2FT+15)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 422`
  
  
  
  
* URL: [http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=0%3Bget-help+%23](http://localhost:8000/api/articles?tag=tag&author=author&favorited=favorited&limit=20&offset=0%3Bget-help+%23)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 422`
  
  
  
  
* URL: [http://localhost:8000/api/articles/feed?limit=20&offset=0%27%3Bsleep+15%3B%27](http://localhost:8000/api/articles/feed?limit=20&offset=0%27%3Bsleep+15%3B%27)
  
  
  * Method: `GET`
  
  
  * Evidence: `HTTP/1.1 403`
  
  
  
  
Instances: 435
  
### Solution
<p></p>
  
### Reference
*

**Comment by nsidnev** [comment]
Closed as stale. If anyone still wants to submit a fix PR with that, they can safely do so, although I'll archive this repository soon, so I'm not sure if it will be useful.
