### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by futurexx** [nsidnev/fastapi-realworld-example-app#258]
HI!

I found ways to fix the typing in several places where now is "type: ignore". Can I suggest my PR that solves this? How can I do this?

**Comment by nsidnev** [comment]
Hi! Sorry I haven't responded for a while, I don't check this repository very often nowadays.

> Can I suggest my PR that solves this? How can I do this?

Yeah, of course you can, if you still want to do it! Just make the necessary changes and mention me directly in the PR. I'll review it as soon as I see a notification in GitHub. Thanks!

**Comment by nsidnev** [comment]
Closed as stale. If you still want to submit a PR, feel free to do that, though I'll archive this repository soon, so I'm not sure if it will be useful.
