### ISSUE TITLE
User registration failed "relation "users" does not exist"

### ISSUE THREAD

**Issue by Eternal-Engine** [nsidnev/fastapi-realworld-example-app#270]
Dear nsidnev,

I'm a fan of your architecture in this application. Unfortunately, I cannot figure out the error from the registration side:

"asyncpg.exceptions.UndefinedTableError: relation "users" does not exist"

I attached an image on how it looks like. I hope we could figure this out.
![Screenshot 2022-04-16 at 13 20 44](https://user-images.githubusercontent.com/65780729/163673049-b2cceef6-88aa-4653-9663-9e9d74565eab.png)

<img width="1356" alt="Screenshot 2022-04-16 at 13 21 56" src="https://user-images.githubusercontent.com/65780729/163673079-8dacd2d0-c3e3-46b3-ac35-bb2e333519b1.png">

Cheers and stay healthy.

**Comment by nsidnev** [comment]
Hi! It looks like the database connected to your local project has the wrong schema. Did you apply alembic migrations before starting the server? Can you show how your database schema looks like?

**Comment by Eternal-Engine** [comment]
Dear Nik,

thank's for replying! I am a big fan of your work. I'm using it as
aguideline to create my university project (software engineering). Genius
layered concept of software, I'm amazed!

My name is Nino and I'm a student in Berlin. I have found out a lot of
stuff from your code and try to recreate them wirg TDD (yes I tested almost
everything, so I understand how they work). I have a lot of questions
related to the tables creation. I saw your alembic and since its asyncpg,
we don't have a fully automated migration, but what is the role of Pypika
tables and queries.pyi? Would you have time to have a call and give a small
tour from your code? My team and I have a deadline on the 2nd of May (yes a
bit too late 😅), but if you would, that would be a great releave and help
us a lot.

Wish you a great day and stay healthy,

Best regards,
Nino

**Comment by nsidnev** [comment]
> Would you have time to have a call and give a small tour from your code?

I don't mind :) 
Email me at sidnev.nick@gmail.com so we can discuss further details there.
