### ISSUE TITLE
Question: Where do you inject Request?

### ISSUE THREAD

**Issue by JonathanLoscalzo** [nsidnev/fastapi-realworld-example-app#294]
I was reading your code, but I don't understand where this method receives _Request_ argument: 

https://github.com/nsidnev/fastapi-realworld-example-app/blob/dc1aa666aa200f6a719bc4374aa8f2f94755e427/app/api/dependencies/database.py#L11

Because: 
- I assume that request is a "global" var in starlette 
- It doesn't have any Depend. 

Note: If you want to label this issue as _question_

**Comment by nsidnev** [comment]
This is a FastAPI [feature](https://fastapi.tiangolo.com/advanced/using-request-directly/#use-the-request-object-directly) that allows you to manually inspect request/websocket data. Therefore it doesn't need `Depends` for the parameter in the function.
