### ISSUE TITLE
Unsupported authorization type

### ISSUE THREAD

**Issue by samanyougarg** [nsidnev/fastapi-realworld-example-app#30]
Hi,

Thank you for creating this project.

Can you please let me know how I can authenticate in the Swagger UI?

Here's what I am doing right now:
1. POST username and email to `/api/users/login` which returns a `TOKEN`.
2. I click on the authorize button in the UI and enter `Token  TOKEN`.

But, when I try out any of the endpoints, it gives me `unsupported authorization type` error.

Thank you

**Comment by nurgasemetey** [comment]
For those who found this

![image](https://user-images.githubusercontent.com/4669437/121878986-019ce980-cd15-11eb-8c89-06cca3dcd550.png)

In other words add `Token` as prefix before generated token.
