### ISSUE TITLE
Error status code

### ISSUE THREAD

**Issue by eliusxpol** [nsidnev/fastapi-realworld-example-app#4]
Hi,
I found this repo amazing and very useful.
There is a small issue i noticed in the status code when the app raise an exception; it's sending 200 status code.
I did solve it by adding the exc status code in this line: https://github.com/nsidnev/fastapi-realworld-example-app/blob/8e3e53984e16aab3f9845211d8d9854b893c6001/app/core/errors.py#L15

**Comment by nsidnev** [comment]
Oh, thanks, missed that. Fixed in de9afb1.
