### ISSUE TITLE
Update test running guide

### ISSUE THREAD

**Issue by JasonLee-crypto** [nsidnev/fastapi-realworld-example-app#48]
I think this need some guideline to how to run unit test under the `test` dir for some beginners
It will be very helpful, so much thanks

**Comment by nsidnev** [comment]
Are you talking about this way of using `pytest`?
```bash
$ pytest tests/test_api/test_routes/test_users.py::test_user_can_not_take_already_used_credentials
================================================= test session starts ==================================================
platform linux -- Python 3.8.3, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/user/fastapi-realworld-example-app, inifile: setup.cfg
plugins: env-0.6.2, cov-2.9.0, asyncio-0.12.0
collected 2 items

tests/test_api/test_routes/test_users.py ..                                                                      [100%]

================================================== 2 passed in 8.43s ===================================================
$
```

We can add this example somewhere in readme, as well as add a link to this feature from the `pytest` documentation. Right?

**Comment by JasonLee-crypto** [comment]
yes, but I think the test can only run when the setup is correct i.e. the database host and base api url (when the backend server is running) are setup properly. right now I type your command from above it just stuck with test don't give any output results:
```
pytest tests/test_api/test_routes/test_users.py::test_user_can_not_take_already_used_credentials                                               
platform darwin -- Python 3.7.4, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /Users/jason.li/project/python/fastapi-realworld-example-app, inifile: setup.cfg
plugins: cov-2.9.0, asyncio-0.10.0, env-0.6.2
collected 2 items   
                                                                                                                                                                                                                  
tests/test_api/test_routes/test_users.py 
```

**Comment by nsidnev** [comment]
Hm. I'm actually not sure why the tests are stuck here. I thought this was a docker failure(since tests at startup setup the local version of postgres in docker), but in the case when the fixture can't connect to the daemon to create a new postgres container, it should fail with an error from the docker driver.

Can you try to setup local postgres (possibly also through docker, but with port binding) and run the tests with the following command, please?
```bash
USE_LOCAL_DB_FOR_TEST=True pytest tests/test_api/test_routes/test_users.py::test_user_can_not_take_already_used_credentials
```

**Comment by JasonLee-crypto** [comment]
Thanks, USE_LOCAL_DB_FOR_TEST=True works for me.

**Comment by nsidnev** [comment]
Well, then it seems to me that this is something with a docker or driver for it on OSX. Unfortunately, I don't have a device with OSX, and I can't figure it out in more detail. 
But at least this case can be mentioned in readme.

**Comment by nsidnev** [comment]
@JasonLee-crypto 
Just merged PR, which added a little guide for `pytest` and how to run tests for this project. If this is not enough, then feel free to reopen the issue or send a new PR with additional changes, which in your opinion may be missed.
