### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by rishabh96b** [nsidnev/fastapi-realworld-example-app#50]
It will be great to have a detailed documentation that covers directory structure, app functionalities. This will really help new users to be able to grasp your work easily.

**Comment by nsidnev** [comment]
Hi!

Most of this is already covered in the readme. As for the functionality abilities, then they can be found in the [repository](https://github.com/gothinkster/realworld/tree/master/api#realworld-api-spec), which contains the spec for this backend.

**Comment by nsidnev** [comment]
Closed as stale. If anyone still wants to submit a PR with that, they can safely do so, although I'll archive this repository soon, so I'm not sure if it will be useful.
