### ISSUE TITLE
How to authorize in swagger?

### ISSUE THREAD

**Issue by AndreGuerra123** [nsidnev/fastapi-realworld-example-app#6]
How to add the authorised button next to the endpoint in swagger?
Best regards

**Comment by nsidnev** [comment]
Hello!

I have not played with this part of `FastAPI`, so I am not sure if my answer is correct.  But it seems to me that it is enough to change the dependency, which extracts the header for authorization to a similar one from `fastapi.security`.

**Comment by AndreGuerra123** [comment]
Fair, I thought it was a build-in feature. Regards.

**Comment by nsidnev** [comment]
@AndreGuerra123 Hi! I recently refactored this project and added authorization support in swagger. If you are still interested, then you can find the implementation [here](https://github.com/nsidnev/fastapi-realworld-example-app/blob/master/app/api/dependencies/authentication.py).
