### ISSUE TITLE
How can I run this app on Google app engine without requirements.txt 

### ISSUE THREAD

**Issue by udiNur** [nsidnev/fastapi-realworld-example-app#97]
Hi there.

I start using fastAPI before a few weeks and I love it!
And I read a lot about poetry, and I get the idea, but I still not managed to deploy this app to Google app engine engine, because the requirements file is missing.

I try to digging into it, but I fill that I missed something, especially in gae, but also in other services and tools that require requirements.txt

Thanks for any help!

**Comment by nsidnev** [comment]
Hi! I haven't worked with GAE, but if the only problem is the missing `requirements.txt` file, then you can generate it using [`poetry`](https://python-poetry.org/docs/cli/#export).

**Comment by udiNur** [comment]
OK, thanks for the kind response!
