### ISSUE TITLE
Can you talk more about how you split queries between aiosql and pypika?

### ISSUE THREAD

**Issue by npalladium** [nsidnev/fastapi-realworld-example-app#98]
This repository has shown me a very interesting way of organsing the db logic and I'm interested in the reasons behind your decisions. Thank you! (It's really amazing work and really helpful.)

**Comment by nsidnev** [comment]
Hi! Sorry for the long delay, it has been a busy week.

I'm not sure what to say specifically about the approach in this project, so I'll first talk about how I got to this solution and then the pros and cons (I use it slightly modified in my other projects as well).

At first I only used raw SQL strings in this project and it worked (especially with pycharm which has good DB integration). But reading such code in github was not easy, and also some of these SQL string simply could not be read (where dynamic queries were required). So, to fix the first issue, I used aiosql, which helped me move all static queries into separate files, which gives me all the pros described in the aiosql docs. But dynamic queries were still a problem, so I wanted to use pypika for that. To make the refactoring a little easier and compatible with the current project settings, I added typings to pypika and after that I already rewrote the generation of dynamic requests with it.

So in the end I got the following pros:
1. Static queries are placed in .sql files with comments, highlighting and much better IDE integration.
2. After mapping them to python code, I also have typings, which is nice feature.
3. Dynamic queries are processed by readable pypika queries with typed tables.

But there are also a few cons (which IMO are not that important compared to the pros):
1. You need to write some boilerplate code to define queries (write a query to a .sql file, write a signature in a typed mapper, add typed tables for pypika).
2. Multiple tools for a similar task compared to only ORM approach.


> (It's really amazing work and really helpful.)

Thanks! :)

**Comment by npalladium** [comment]
Thanks! That was pretty illuminating.
I'm working on a project with a relatively small number of credits where it queries would only get added but not edited. I initially intended to write every version of the "dynamic queries" by hand. Then I ran into this project and the use of pypika.

PS. Could you tell why you chose to work without an ORM?

**Comment by nsidnev** [comment]
> Could you tell why you chose to work without an ORM?

Well, there are 2 reasons for this:
1. At the time of this project writing, there was no good async ORM for python. The Tortoise-ORM was very young (and remains so), SQLAlchemy did not have support for async, orm from encode also had limitations (for example, m2m fields). There was a Gino, but that was not what I was looking for, although it is also a good project.
2. I used to work with SQLAlchemy, and on this project I just wanted to try the other side of working with the database. So at some point it's just IMO :)

FYI. If I were writing this project now, then I think I'd try SQLAlchemy 1.4, which out of the box supports asyncpg.

**Comment by ZXiangQAQ** [comment]
Hi! Do you plan to refactor this repository with SQLAlchemy 1.4?

**Comment by nsidnev** [comment]
@ZXiangQAQ hi, sorry for long delay, I was busy.

> Do you plan to refactor this repository with SQLAlchemy 1.4?

Sorry, but no. I'd like to keep current implementation for DB part.
